version: '3'

services:
  analyze:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
